version: "3"

services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - web

  web:
    build: ./web_app
    env_file: ./my.env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./web_app:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    env_file: ./my.env
    ports:
      - "5455:5432"